<?php
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
?>
<h3>Add plugin</h3>
    <div class="row">
        <div class="col col-sm-6">
            <?= $this->partial('layout/flash.phtml'); ?>
            <form method="post" action="" enctype="multipart/form-data">
            <div class="form-group">
                <label>Plugin attributes from maven.org's <code>maven-metadata.xml</code> </label>
            </div>
            <div class="form-group">
                <label for="urgroupIdl">GroupId</label>
                <input type="text" class="form-control" id="groupId" name="groupid" placeholder="com.project" value="<?= $this->plugin->getGroupId() ?>" style="width: 400px;">
            </div>
            <div class="form-group">
                <label for="url">ArtifactId</label>
                <input type="text" class="form-control" id="artefictid" name="artifactid" placeholder="artifactId" value="<?= $this->plugin->getArtifactId() ?>" style="width: 400px;">
            </div>
            <button type="submit" class="btn btn-primary">Add Plugin</button>
            </form>
        </div>
    </div>