<?php
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
?>
<?php
$h = 'Sorry, no plugin found';
if ($this->plugin) {
    $h = $this->plugin->getName();
} 
echo '<h3 class="text-primary">'.$h.'</h3>';

if ($plugin) {
    echo '
    <div class="row">
    <div class="col-md-6">
    <p>
    <p>ArtifactId: <b>'.$plugin->getArtifactId().'</b> &nbsp;&nbsp;
    ';

        foreach ($plugin->getVersions() as $v) {
            echo '<span class="badge">'.$v->getVersion().'</span> &nbsp;';
        }    
        
    echo '</p>
    <p>Author: <b>'.$plugin->getAuthor()->getName().'</b></p>
    <p>License: <b>'.$plugin->getLicense().'</b></p>
    <p>Homepage: <a href="'.$plugin->getHomepage().'">'.$plugin->getHomepage().'</a></p>
    <p>
        <i class="fas fa-asterisk"></i> '.$plugin->getAddedAt()->format('Y-m-d').' &nbsp; &nbsp;
        <i class="fas fa-edit"></i> '.$plugin->getLastUpdatedAt()->format('Y-m-d').' &nbsp; &nbsp;
        <i class="fas fa-download"></i> '.number_format($plugin->getDownloads()).' 
    </p>
    <p>';

        foreach ($plugin->getCategories() as $cat) {
            echo '<span class="badge badge-blue">'.$cat->getName().'</span> &nbsp;';
        }    
    echo '</p> 
    <br/><h4 class="text-primary">Download matrix</h4>
    <table class="table table-striped table-hover" style="width:auto">
    <thead>
        <tr>
        <th>Plugin version</th>
        <th>NetBeans compatible</th>
        </tr>
        </thead>
        <tbody>
        ';
        foreach ($plugin->getVersions() as $version) {
            echo '<tr><td><span class="badge">'.$version->getVersion().'</span></td><td>';
            foreach ($version->getNbVersionsPluginVersions() as $nbvPv) {
                if ($nbvPv->getVerificationId()) {
                    echo '<span class="badge '.$nbvPv->getVerification()->getStatusBadgeClass().'">
                    <a href="./download?id='.$version->getId().'" title="Download" target="_blank" class="dllink"><i class="fas fa-download"></i> NB '.$nbvPv->getNbVersion()->getVersion().'</a> 
                    - <span class="verifPopupLink" data-toggle="modal" data-verification-id="'.$nbvPv->getVerification()->getId().'" data-target="#verifPopup" title="Show verification details">'.$nbvPv->getVerification()->getStatusBadgeTitle().'</span></span> &nbsp; ';
                } else {
                    echo '<a href="./download?id='.$version->getId().'" title="Download" target="_blank"><span class="badge badge-brown"><i class="fas fa-download"></i> NB '.$nbvPv->getNbVersion()->getVersion().'</span></a> &nbsp; ';
                }
            }
            echo ' </td></tr>';
        }
        echo '</tbody>
        </table>
        </div>
        <div class="col-md-6">';
        if($plugin->getImage()) {
            echo '<div><img src="../data/plugins/'.$plugin->getId().'/'.$plugin->getImage().'" style="max-width: 100%;"/></div>';
        }    
    echo '</div>
        </div>
    <br/>
    <div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Intro</h3>
    </div>
    <div class="panel-body">
        '.$plugin->getShortDescription().'
    </div>
    </div>
    <br/>
    <div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Description</h3>
    </div>
    <div class="panel-body">
        '.$plugin->getDescription().'
    </div>
    </div>
    <br/>
    ';
}
?>

<div class="modal fade" id="verifPopup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Plugin verificaion log</h4>
            </div>
            <div class="modal-body" id="verifBody">        
            </div>
        </div>
    </div>
</div>    