<?php
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
?>
<?php
$flash = $this->flashMessenger();
$flash->setAutoEscape(false);
$flash->setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
    &times;
</button>
<div>')->setMessageCloseString('</div></div>');
echo $flash->renderCurrent('error', array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->renderCurrent('info', array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->renderCurrent('default', array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->renderCurrent('success', array('alert', 'alert-dismissable', 'alert-success'));
?>