
  <div class="row">
    <div class="col-sm-3">
      <form action="" method="post">
        <div class="form-group">
          <label for="exampleInputEmail1">Email</label>
          <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Email">
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Heslo</label>
          <input type="password" class="form-control" id="password" placeholder="Heslo">
        </div>
        <button type="submit" class="btn btn-primary">Přihlásit</button>
      </form>
    </div>   
  </div>
