<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Login Provider</h3>
    </div>
    <div class="panel-body">
        <ul class="list-group" id="loginProviderList">
            <?php foreach ($this->providers as $p) { ?>
                <li class="list-group-item">
                    <a href='<?= htmlentities($p['loginUrl'], ENT_HTML5, 'UTF-8') ?>' style='display: block'>
                        <div style='background-image: url(<?= htmlentities($p['iconUrl'], ENT_HTML5, 'UTF-8') ?>);' class="providerIcon"></div>
                        <?= htmlentities($p['name'], ENT_HTML5, 'UTF-8') ?>
                    </a>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>