<?php
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
?>
<select name="<?= $this->fieldName?>" class="form-control" <?= $this->required ? 'required' : ''?> >
<option>Select category</option>
<?php
foreach ($this->categories as $cat) {
    if ($this->selected) {
        $sel = $cat->getId() == $this->selected->getId() ? 'selected' : '';
    } else {
        $sel = '';
    }
    echo '<option value="'.$cat->getId().'" '.$sel.'>'.$cat->getName().'</option>';
}
?>
</select>