#!/bin/sh

# Remove externally installed nbjavac references from the userdir
find ${SNAP_USER_DATA} -name '*nbjavac.*' -delete || true
find ${SNAP_USER_DATA} -name '*nbjavac-*' -delete || true

exec $@

