<?php
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
?>
    <div class="form-group">
        <label for="url">Url</label>
        <input type="text" class="form-control" id="url" name="url" required placeholder="" value="<?= $this->pluginVersion->getUrl() ?>" readonly="true">
    </div>
    <div class="form-group">
        <label for="version">Version</label>
        <input type="text" class="form-control" id="version" name="version" placeholder="" value="<?= $this->pluginVersion->getVersion() ?>" readonly="true">
    </div>
    <?php if (! $this->pluginVersion->getErrorMessage()) { ?>
    <div class="form-group">
        <label for="relnotes">Release notes <span class="text-primary"></span></label>
        <textarea class="form-control" id="relnotes" name="relnotes" rows="5"
        placeholder="Release notes"><?= $this->pluginVersion->getRelnotes() ?></textarea>
    </div>
    <div class="form-group">
        <label for="url">NetBeans version</label>
        <?= $this->partial('partials/_nbVersion-select.phtml',
                array('nbVersions' => $this->nbVersions, 'pluginVersion' =>$this->pluginVersion, 'verifiedNbVersionIds'=>$this->verifiedNbVersionIds, "verificationPendingNbVersionIds" => $this->verificationPendingNbVersionIds)); ?>
    </div>
    <?php } ?>