    <div class="form-group">
        <label for="url">Url</label>
        <input type="text" class="form-control" id="url" name="url" required placeholder="" value="<?= $this->pluginVersion->getUrl() ?>" readonly="true">
    </div>
    <div class="form-group">
        <label for="version">Version</label>
        <input type="text" class="form-control" id="version" name="version" placeholder="" value="<?= $this->pluginVersion->getVersion() ?>" readonly="true">
    </div>
    <div class="form-group">
        <label for="relnotes">Release notes <span class="text-primary"></span></label>
        <textarea class="form-control" id="relnotes" name="relnotes" rows="5"
        placeholder="Release notes"><?= $this->pluginVersion->getRelnotes() ?></textarea>                
    </div>
    <div class="form-group">
        <label for="url">NetBeans version</label>
        <?= $this->partial('partials/_nbVersion-select.phtml', 
                array('nbVersions' => $this->nbVersions, 'pluginVersion' =>$this->pluginVersion, 'verifiedNbVersionIds'=>$this->verifiedNbVersionIds)); ?>
    </div>