<h3><span class="text-primary"><?= $this->pluginVersion->getPlugin()->getName()?> <?= $this->pluginVersion->getVersion()?></span> - version management</h3>
    <div class="row">
        <div class="col col-sm-6">
            <?= $this->partial('layout/flash.phtml'); ?>
            <form method="post" action="" class="needs-validation">
            <?php 
            echo $this->partial('application/plugin-version/_pluginVersion-form.phtml', 
            array('pluginVersion' => $this->pluginVersion, 'nbVersions' => $this->nbVersions, 'verifiedNbVersionIds' => $this->verifiedNbVersionIds)); 
            ?>
            <a class="btn btn-secondary" href="../plugin/list" role="button">Return</a>
            <button type="submit" class="btn btn-primary">Save Plugin Version</button>
            </form>
            
        </div>
    </div>
    <br/>