<?php
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
?>
<h3><span class="text-primary"><?= $this->pluginVersion->getPlugin()->getName()?> <?= $this->pluginVersion->getVersion()?></span> - version management</h3>
    <div class="row">
        <div class="col col-sm-6">
            <?= $this->partial('layout/flash.phtml'); ?>
            <form method="post" action="" class="needs-validation">
            <?php 
            echo $this->partial('application/plugin-version/_pluginVersion-form.phtml', 
            array('pluginVersion' => $this->pluginVersion, 'nbVersions' => $this->nbVersions, 'verifiedNbVersionIds' => $this->verifiedNbVersionIds)); 
            ?>
            <?php
            if($this->pluginVersion->getErrorMessage()) {
            echo $this->partial('application/plugin-version/_pluginVersion-error-report.phtml', 
            array('pluginVersion' => $this->pluginVersion, 'nbVersions' => $this->nbVersions, 'verifiedNbVersionIds' => $this->verifiedNbVersionIds));
            }
            ?>
            <a class="btn btn-secondary" href="<?= $this->return ?>" role="button">Return</a>
            <?php if (! $this->pluginVersion->getErrorMessage()) { ?>
            <button type="submit" class="btn btn-primary">Save Plugin Version</button>
            <?php } ?>
            </form>
            
        </div>
    </div>
    <br/>