<?php
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
?>
<h3>Admin tools</h3>
<p class="admin-nav">
<a href="<?= $this->url('admin', array('action' => 'index'))?>">Find & Edit Plugin</a>
<a href="<?= $this->url('admin', array('action' => 'approve'))?>">Plugins waiting for approval</a>
<a href="<?= $this->url('admin', array('action' => 'catalog'))?>">Publish catalog</a>
<a href="<?= $this->url('admin', array('action' => 'verifiers'))?>">Verifiers</a>
<a href="<?= $this->url('admin', array('action' => 'categories'))?>">Plugin categories</a>
<a href="<?= $this->url('admin', array('action' => 'nb-versions'))?>">NetBeans versions</a>
</p>
<hr/>