<h3>Admin tools</h3>
<p class="admin-nav">
<a href="<?= $this->url('admin', array('action' => 'index'))?>">Find & Edit Plugin</a>
<a href="<?= $this->url('admin', array('action' => 'approve'))?>">Plugins waiting for approval</a>
<a href="<?= $this->url('admin', array('action' => 'catalog'))?>">Publish catalog</a>
<a href="<?= $this->url('admin', array('action' => 'verifiers'))?>">Verifiers</a>
<a href="<?= $this->url('admin', array('action' => 'categories'))?>">Plugin categories</a>
<a href="<?= $this->url('admin', array('action' => 'nb-versions'))?>">NetBeans versions</a>
</p>
<hr/>