<?php
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
?>
<?php
$versionBadges = array();
foreach ($plugin->getVersions() as $version) {
    $versionBadges[]='<span class="badge">'.$version->getVersion().'</span>';
}

/* @var $plugin Application\Entity\Plugin */
$authors = [];
foreach($plugin->getAuthors() as $author) {
    $authors[] = htmlspecialchars($author->getName(), ENT_COMPAT, "UTF-8");
}

echo '
<h4 class="text-primary"><a href="'.$this->url('admin', array('action' => 'edit'),array('query' => array('id'=>$plugin->getId()))).'">'.$plugin->getName().'</a></h4>
<p>
    '.implode('&nbsp;', $versionBadges).'
</p>
<table role="presentation">
    <tr><td style="padding-right: 1ex">Status:</td><td><b>'.$plugin->getStatusTitle().'</b></td></tr>
    <tr><td style="padding-right: 1ex">ArtifactId:</td><td><b>'.$plugin->getArtifactId().'</b></td></tr>
    <tr><td style="padding-right: 1ex">Author:</td><td><b>'. implode("<br />", $authors) .'</b></td></tr>
</table>
<p>
<i class="fas fa-asterisk"></i> '.$plugin->getAddedAt()->format('Y-m-d').' &nbsp; &nbsp;&nbsp; 
<i class="fas fa-edit"></i> '.$plugin->getLastUpdatedAt()->format('Y-m-d').'   &nbsp; &nbsp;  &nbsp;            
<i class="fas fa-file-contract"></i> '.$plugin->getLicense().'
</p>
<p>';

foreach ($plugin->getCategories() as $cat) {
    echo '<span class="badge badge-blue">'.$cat->getName().'</span> &nbsp;';
}    
echo '</p>';
?>