<?php
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
?>
<?= $this->partial('_nav.phtml'); ?>
<h4>Plugins waiting for approval</h4>
<p>
<?= $this->partial('layout/flash.phtml'); ?>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Plugin</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
<?php
    foreach ($this->plugins as $plugin) {
        $versionBadges = array();
        foreach ($plugin->getVersions() as $version) {
            $versionBadges[]='<span class="badge">'.$version->getVersion().'</span>';
        }
        echo '<tr>
            <td>
               '.$this->partial('_pluginRowItem.phtml', array('plugin' => $plugin)).'
            </td>
            <td>
                '.$plugin->getDescription().'
            </td>
            <td>
                <p>
                <a class="btn btn-success" href="'.$this->url('admin',array('action'=>'approve'),array('query' => array('id'=>$plugin->getId()))).'" role="button" title="Approve">
                    Approve
                </a>
                </p>
                <p>
                <a class="btn btn-danger" href="'.$this->url('admin',array('action'=>'delete-pending'),array('query' => array('id'=>$plugin->getId()))).'" role="button" title="Publish">
                    Delete
                </a>
                </p>
            </td>
        </tr>';
    }
?>
    </tbody>
</table>