<?php
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
?>
<?= $this->partial('_nav.phtml'); ?>
<h4>Publish catalog</h4>
<p>
<?= $this->partial('layout/flash.phtml'); ?>
</p>
<table class="table table-striped table-hover">
<?php
    foreach ($this->nbVersions as $nbv) {
        echo '<tr>
            <td><h4>NB '.$nbv->getVersion().'</h4></td>
            <td>
                <a href="'.$this->catalUrlPath.'/'.$nbv->getVersion().'/catalog.xml" target="_blank">View catalog</a><br/>
                <a href="'.$this->catalUrlPath.'/'.$nbv->getVersion().'/catalog-experimental.xml" target="_blank">View experimental catalog</a>
            </td>
            <td>
                <a class="btn btn-primary" href="'.$this->url('admin',array('action'=>'catalog'),array('query' => array('version'=>$nbv->getVersion()))).'" role="button" title="Approve">
                    Publish catalog
                </a>
                &nbsp;
                <a class="btn btn-primary" href="'.$this->url('admin',array('action'=>'catalog'),array('query' => array('version'=>$nbv->getVersion(), 'experimental' => true))).'" role="button" title="Approve">
                Publish experimental catalog
            </a>
            </td>
        </tr>';
    }
?>
</table>