<h3>Edit Plugin</h3>
    <div class="row">
        <div class="col col-sm-6">
            <?= $this->partial('layout/flash.phtml'); ?>
            <form method="post" action="" class="needs-validation" enctype="multipart/form-data">
            <?= $this->partial('application/plugin/_plugin-form.phtml', array('plugin' => $this->plugin, 'categories' => $this->categories)); ?>
            <a class="btn btn-secondary" href="<?= $this->url('admin')?>" role="button">Return</a>
            <button type="submit" class="btn btn-primary">Save Plugin</button>
            </form>
            
        </div>
    </div>