<?php
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
?>
<?= $this->partial('_nav.phtml'); ?>
<h4>NetBeans versions</h4>
<p>
<?= $this->partial('layout/flash.phtml'); ?>
</p>
<p>
<form class="form-inline" method="post" action="">
  <div class="form-group">
    <label for="exampleInputName2">New version: </label>
    <input type="text" class="form-control" name="version" id="search" placeholder="NetBeans version" style="width: 300px;" value="">
  </div>
  <button type="submit" class="btn btn-primary">Add version</button>
</form>
</p>
<br/>
<table class="table table-striped table-hover" style="width: 50%">
<?php
    foreach ($this->nbVersions as $v) {
        echo '<tr>
            <td><h5>'.$v->getVersion().'</h5></td>            
            <td>
                <a class="btn btn-danger" href="'.$this->url('admin',array('action'=>'nb-versions'),array('query' => array('id'=>$v->getId()))).'" role="button" title="Delete">
                    Delete
                </a>
            </td>
        </tr>';
    }
?>
</table>